### ISSUE TITLE
Does this line work?

### ISSUE THREAD

**Issue by amazingproducer** [VictorLepesh/css-Tests#1]
https://github.com/VictorLepesh/css-Tests/blob/54d9e0f440fd1ef6b9827e4d994e8eff093b6d7b/css%20Cheat%20sheet/index.html#L59

**Comment by VictorLepesh** [comment]
Oh no, that was so I can test the :visited selector at 33 in style.css in cheatsheet.  Sorry for the late reply, not familiar with issues.
